name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      #DOCKER_REGISTRY: kemansel.azurecr.io      
      DOCKER_IMAGE: sky360/cyclop 
      DOCKER_USER: ${{secrets.DOCKER_USER}} 
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      DOCKER_TARGET_PLATFORM: linux/arm/v7      
    steps:
    - uses: actions/checkout@v3 
    - name: docker login
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Build the Docker image
      run: |
        docker buildx build ./Docker/cyclop/ \        
          --platform ${DOCKER_TARGET_PLATFORM} \
          --tag ${DOCKER_IMAGE}:${GITHUB_RUN_NUMBER} \
          --tag ${DOCKER_IMAGE}:latest
        
    - name: Docker Push
      run: docker push ${DOCKER_IMAGE}:latest
    
    
