name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Cyclop Docker image
      run: docker build . --file Docker/cyclop/Dockerfile --tag sky360/cyclop:$(date +%s)
